### PR TITLE
Updated the whole solution so it can work on any screen

### PR DESCRIPTION
**Pull request by DaXmAn**
If you like to, you can merge my version with your repo...

### CODE REVIEW

**Comment by Pimeko** [comment]
Awesome, thanks for that!

**Comment by Pimeko** [comment]
I've let your name in the Author section, simply left the description as it was to fit with Lively's logic ;)

**Comment by DaXmAn** [comment]
you may want to update the release, it's still providing older version of the wallpapaer :)

**Comment by Pimeko** [comment]
You're right, done and thanks :)

**Pull request merged**
